### ISSUE TITLE
It's not able to read datetime cell 

### ISSUE THREAD

**Issue by abcdef123ghi** [igormironchik/read-excel#1]
Hello sir
    I have try to read a cell which is datetime type,it doesn't work 
wstring availdatew = sheet->cell(0, 6).getString();
availdatew is  empty when using getString() method,thanks

**Comment by igormironchik** [comment]
Hello,

Date and time in Excel BIFF8 is a count of days since 1899-Dec-31 or 1904-Jan-01. So date and time you should get with getDouble(), and the date value 1 represents 1900-Jan-01 if base date is 1899-Dec-31.

I added Excel::Book::dateMode() method, so now you can handle date and time mode.

I released version 1.1.2 today where were fixed different issues, so read-excel now compiles with C++11, fixed issue with short streams, added different checks.

And, sure, you can look at the example where you can find example of date and time usage.

**Comment by abcdef123ghi** [comment]
thank you very much,you are awsome,I'm very appreciated

**Comment by abcdef123ghi** [comment]
BTW,you need add following in formula.hpp,string.hpp
include  cstdint 
the Visual Studio is gonna occur error if you don't add such header in version which is 2013
